### PR TITLE
Auto-escaped convenience methods for filters

### PR DESCRIPTION
**Pull request by Jamstah**
Hi guys,

Here are some methods for creating filters that are more painless for the developer. They automatically escape their values so are suitable for taking input straight from the user.

I added a test for the methods, which also tests the escaping.

DN's also need escaping in ldap, but I'll probably add a new pull request for that as and when I have something ready.

James.

### CODE REVIEW

**Comment by Jamstah** [comment]
I thought I'd just add the DN class to this request, as it handles escaping. Its currently a convenience class, and isn't used within the main code. I think by careful addition of .to_s on dn arguments, the api can go on accepting Strings as dns, as well as accepting DN objects.

**Comment by Jamstah** [comment]
Just realised we don't need to_s on dn arguments anywhere if we just proxy the escaped DN string within the DN class. This way, the current code can stay as is, but people can use DN objects wherever they were using DN strings. Seeing as a DN is really just a string, this makes sense anyway, as people might want to use the string methods on them.

**Comment by kschiess** [comment]
After some deliberation, I find the first patch to be quite useful. I am not so sure about the addition of the DN class though. I'll pull the first commit (after some testing) and will leave the others open for discussion.

**Comment by Jamstah** [comment]
Great.

What is it you don't like about the DN class? I think there definitely need to be some methods for escaping and parsing DN's in the library, and I tried to do it in a way which would be backwards compatible and obvious how to use.

I couldn't think of a better way to incorporate it, anyway. Did you have any other plans?

James.

**Comment by kschiess** [comment]
I did want a second opinion that is all ;). I don't claim to be the single ruler of this project, so I don't have to take all the hard decisions myself. I've posted to the list about this: http://groups.google.com/group/ruby-ldap/browse_thread/thread/d170acb7441a680b

**Comment by Jamstah** [comment]
Ah, I didn't realise there was a list. I guess I should sign up myself.

**Comment by Jamstah** [comment]
Kaspar, when you changed the escape mechanism to be 1.9 compatible, you changed the characters that were being escaped. It didn't get picked up by the tests I put in, because you didn't pull in the tests either :)

I've changed characters in the new mechanism to what they should be.

**Comment by kschiess** [comment]
The RFC on LDAP cites different characters; I reworked from that. So yours got dropped, and I am sorry for that. Looks like we have to think about what should get escaped more thoroughly, since I think both yours and mine make sense!

When you patch up the code, please try to fix the specs at the same time as the relevant code; and also remember to keep merge commits to a minimum. I'll look at the changes in a day or two, but I'll probably just include your set into mine instead of pulling 6 changes...

**Comment by Jamstah** [comment]
A bit new to git, this pull request has got a bit much. Was thinking of deleting this branch and putting in two (one for filters and one for dns) that were more sensible.

A bit new to rspec too, which is why I just updated the tests. I'm learning, so have been updating that in my other branches :)

Are you sure you read the spec right? I think it says the value can be of the UTF1SUBSET, or escaped, and the subset excludes only nul, lparen, rparen, asterisk, and esc. The other characters below are just definitions that are used further up the ABNF, but are still valid in attribute values.

The escape method is only used on the value at the moment, a different method might be needed for the attribute.

Let me know if you want me to split there changes into branches for you.

Here's an extract:

```
  valueencoding  = 0*(normal / escaped)
  normal         = UTF1SUBSET / UTFMB
  escaped        = ESC HEX HEX
  UTF1SUBSET     = %x01-27 / %x2B-5B / %x5D-7F
                      ; UTF1SUBSET excludes 0x00 (NUL), LPAREN,
                      ; RPAREN, ASTERISK, and ESC.
  EXCLAMATION    = %x21 ; exclamation mark ("!")
  AMPERSAND      = %x26 ; ampersand (or AND symbol) ("&")
  ASTERISK       = %x2A ; asterisk ("*")
  COLON          = %x3A ; colon (":")
  VERTBAR        = %x7C ; vertical bar (or pipe) ("|")
  TILDE          = %x7E ; tilde ("~")
```

**Comment by Jamstah** [comment]
Reading the spec some more, it looks like we should escape non-ascii characters, or just force strings to utf8 if they are using 1.9.

```
 As indicated by the <valueencoding> rule, implementations MUST escape
 all octets greater than 0x7F that are not part of a valid UTF-8
 encoding sequence when they generate a string representation of a
 search filter.  Implementations SHOULD accept as input strings that
 are not valid UTF-8 strings.  This is necessary because RFC 2254 did
 not clearly define the term "string representation" (and in
 particular did not mention that the string representation of an LDAP
 search filter is a string of UTF-8-encoded Unicode characters).
```

**Comment by kschiess** [comment]
Also, if we want to provide an injection-proof escape method, we need to not only escape illegal characters, but also characters that have meaning, such as '*', '!', etc... Hence the set of characters I added. 

I would very much welcome a patch based on the current master that extends the set of escaped characters. I can't provide one myself right now. As is, the feature should not be released; Jamstah is absolutely right by objecting to the current solution.

**Comment by Jamstah** [comment]
Closing this request, as it has now been split into two more sensible requests.

**Pull request closed without merging**
